// track-and-field/components/atoms/Container.vue
<template>
  <div
    class="atoms-container"
    :style="{ 'max-width': maxWidth + 'px', padding: padding }"
  >
    <slot></slot>
  </div>
</template>

<script lang="ts">
import { defineComponent } from '@nuxtjs/composition-api';

export default defineComponent({
  props: {
    maxWidth: {
      type: Number,
      default: 1280
    },
    padding: {
      type: String,
      default: null
    }
  },
  setup() {}
});
</script>

<style lang="scss" scoped>
.atoms-container {
  width: 100%;
  max-width: 900px;
  margin-left: auto;
  margin-right: auto;
}
</style>

// picker-app/src/component/atoms/Container.tsx
import React, { type FC, PropsWithChildren } from 'react';
import { css } from '@emotion/css';
import { Size } from 'shared/types/style-props';

type Props = {
  maxWidth?: Size;
  sidePadding?: Size;
};

export const Container: FC<PropsWithChildren<Props>> = ({ children, maxWidth = '1440px', sidePadding = '16px' }) => (
  <div
    className={css`
      width: 100%;
      max-width: ${maxWidth};
      padding-right: ${sidePadding};
      padding-left: ${sidePadding};
      margin-right: auto;
      margin-left: auto;
    `}
  >
    {children}
  </div>
);
